openapi: 3.0.0
info:
  version: 1.0.0
  title: StoreCraft API
  description: This is the API
servers:
  - url: v1
security: []
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: string
          description: ID
        created_at:
          type: string
          description: ISO string creation time
        updated_at:
          type: string
          description: ISO string update time
        handle:
          type: string
          description: the key name
        values:
          type: array
          items:
            type: string
          description: list of values
      required:
        - handle
        - values
      description: hola
    TagUpsert:
      type: object
      properties:
        id:
          type: string
          description: ID
        handle:
          type: string
          description: the key name
        values:
          type: array
          items:
            type: string
          description: list of values
      required:
        - handle
        - values
  parameters: {}
paths:
  /tags/{id_or_handle}:
    get:
      description: Get tag data by its id or handle
      summary: Get a single tag
      parameters:
        - schema:
            type: string
            example: tag_djsidisjdisd or genre
          required: true
          name: id_or_handle
          in: path
      responses:
        "200":
          description: Object with user data.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
        "204":
          description: No content - successful operation
  /tags:
    post:
      description: upsert a tag
      summary: upsert a single tag
      requestBody:
        description: blah description
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagUpsert"
      responses:
        "200":
          description: ID of upserted data
          content:
            application/json:
              schema:
                type: string
        "204":
          description: No content - successful operation
