# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: ./docs.openapi.yaml
extends:
  - recommended
rules:
  no-unused-components: error
theme:
  openapi:
    theme:
      colors:
        primary:
          main: "#000000"
          light: "#000000"
          dark: "#000000"
        accent:
          main: "#000000"
          light: "#000000"
          dark: "#000000"
        http:
          get: "#FF0000"
    generateCodeSamples:
      languages:  # Array of language config objects; indicates in which languages to generate code samples.
        - lang: curl
        - lang: Node.js
        - lang: JavaScript
        - lang: PHP
        - lang: Python