// Generated by ts-to-zod
import { z } from "zod";
const baseTypeSchema = z.object({
  updatedAt: z.date().optional(),
  createdAt: z.date().optional(),
  id: z.string().optional(),
});
export const authUserTypeSchema = baseTypeSchema.and(
  z.object({
    email: z.string().optional(),
    password: z.string().optional(),
    confirmed_mail: z.boolean().optional(),
  }),
);
export const addressTypeSchema = baseTypeSchema.and(
  z.object({
    firstname: z.string().optional(),
    lastname: z.string().optional(),
    phone_number: z.string().optional(),
    company: z.string().optional(),
    street1: z.string().optional(),
    street2: z.string().optional(),
    city: z.string().optional(),
    country: z.string().optional(),
    state: z.string().optional(),
    zip_code: z.string().optional(),
    postal_code: z.string().optional(),
  }),
);
export const customerTypeSchema = baseTypeSchema.and(
  z.object({
    firstname: z.string(),
    lastname: z.string(),
    email: z.string(),
    phone_number: z.string().optional(),
    address: addressTypeSchema.optional(),
    tags: z.array(z.string()),
    search_index: z.array(z.string()).optional(),
  }),
);
