#:schema node_modules/wrangler/config-schema.json
name = "calm-term-c64e"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[vars]
MY_VARIABLE = "production_value"


# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "D1"
database_name = "main"
database_id = "afcdb16e-5bb9-4d11-a828-2eaf9949c3cf"
